In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
unemp_county = pd.read_csv("/content/drive/My Drive/Datasets/unemployment-by-county-us/output.csv")
unemp_county.head()

   Year     Month        State         County  Rate
0  2015  February  Mississippi  Newton County   6.1
1  2015  February  Mississippi  Panola County   9.4
2  2015  February  Mississippi  Monroe County   7.9
3  2015  February  Mississippi   Hinds County   6.1
4  2015  February  Mississippi  Kemper County  10.6

In [3]:
df = pd.read_csv("/content/drive/My Drive/Datasets/minwage.csv")
actual_min_wage = pd.DataFrame()

for name, group in df.groupby("State"):
  if actual_min_wage.empty:
    actual_min_wage = group.set_index("Year")[["Low.2018"]].rename(columns = {"Low.2018":name})
  else:
    actual_min_wage = actual_min_wage.join(group.set_index("Year")[["Low.2018"]].rename(columns = {"Low.2018":name}))

actual_min_wage.head()

      Alabama  Alaska  Arizona  ...  West Virginia  Wisconsin  Wyoming
Year                            ...
1968      0.0   15.12     3.37  ...           7.20       9.00     8.64
1969      0.0   14.33     3.19  ...           6.83       8.53     8.19
1970      0.0   13.54     3.02  ...           6.45       8.38     8.38
1971      0.0   12.99     2.89  ...           6.18       8.04     8.04
1972      0.0   12.57     2.80  ...           7.19       8.68     8.98

[5 rows x 55 columns]

In [5]:
import numpy as np

actual_min_wage = actual_min_wage.replace(0, np.NaN).dropna(axis=1)
actual_min_wage.head()

      Alaska  Arkansas  California  ...  West Virginia  Wisconsin  Wyoming
Year                                ...
1968   15.12      1.12       11.88  ...           7.20       9.00     8.64
1969   14.33      1.07       11.26  ...           6.83       8.53     8.19
1970   13.54      7.09       10.64  ...           6.45       8.38     8.38
1971   12.99      6.80       10.20  ...           6.18       8.04     8.04
1972   12.57      7.19        9.88  ...           7.19       8.68     8.98

[5 rows x 39 columns]

In [6]:
def get_min_wage(year, state):
  try:
    return actual_min_wage.loc[year][state]
  except:
    return np.NAN

get_min_wage(2012, 'Colorado')

8.33

In [8]:
%%time

unemp_county['min_wage'] = list(map(get_min_wage, unemp_county['Year'], unemp_county['State']))

CPU times: user 2min 1s, sys: 59 ms, total: 2min 1s
Wall time: 2min 1s

In [25]:
unemp_county[['Rate', 'min_wage']].corr()

              Rate  min_wage
Rate      1.000000  0.153047
min_wage  0.153047  1.000000

In [26]:
unemp_county[['Rate', 'min_wage']].cov()

              Rate  min_wage
Rate      9.687873  0.651586
min_wage  0.651586  1.874228

In [27]:
pres16 = pd.read_csv("/content/drive/My Drive/Datasets/pres16results.csv")
pres16.head()

  county fips             cand  ...  total_votes       pct          lead
0    NaN   US     Donald Trump  ...  127592176.0  0.472993  Donald Trump
1    NaN   US  Hillary Clinton  ...  127592176.0  0.477938  Donald Trump
2    NaN   US     Gary Johnson  ...  127592176.0  0.032640  Donald Trump
3    NaN   US       Jill Stein  ...  127592176.0  0.009844  Donald Trump
4    NaN   US    Evan McMullin  ...  127592176.0  0.003540  Donald Trump

[5 rows x 9 columns]

In [31]:
len(unemp_county)

885548

In [0]:
county_2015 = unemp_county.copy()[(unemp_county['Year']==2015) & (unemp_county['Month']=='February')]

In [29]:
pres16['st'].unique()

array(['US', 'CA', 'FL', 'TX', 'NY', 'PA', 'IL', 'OH', 'MI', 'NC', 'GA',
       'VA', 'NJ', 'MA', 'WI', 'MN', 'MO', 'WA', 'IN', 'CO', 'TN', 'MD',
       'SC', 'AL', 'AZ', 'LA', 'KY', 'OR', 'CT', 'IA', 'OK', 'MS', 'KS',
       'NV', 'AR', 'UT', 'NE', 'NM', 'ME', 'NH', 'WV', 'ID', 'MT', 'RI',
       'DE', 'HI', 'SD', 'ND', 'VT', 'DC', 'WY', 'AK', nan], dtype=object)

In [28]:
state_abbv = pd.read_csv("/content/drive/My Drive/Datasets/state_abbv.csv", index_col=0)
state_abbv = state_abbv[["Postal Code"]]
state_abbv.head()

               Postal Code
State/District
Alabama                 AL
Alaska                  AK
Arizona                 AZ
Arkansas                AR
California              CA

In [0]:
state_abbv_dict = state_abbv.to_dict()['Postal Code']

In [0]:
county_2015['State'] = county_2015['State'].map(state_abbv_dict)

In [34]:
county_2015.tail()

      Year     Month State              County  Rate  min_wage
2797  2015  February    ME     Somerset County   8.4      7.92
2798  2015  February    ME       Oxford County   6.8      7.92
2799  2015  February    ME         Knox County   6.1      7.92
2800  2015  February    ME  Piscataquis County   7.0      7.92
2801  2015  February    ME    Aroostook County   7.2      7.92

In [35]:
pres16.columns

Index(['county', 'fips', 'cand', 'st', 'pct_report', 'votes', 'total_votes',
       'pct', 'lead'],
      dtype='object')

In [36]:
pres16.rename(columns={'county':'County', 'st':'State'}, inplace=True)
pres16.head()

  County fips             cand  ...  total_votes       pct          lead
0    NaN   US     Donald Trump  ...  127592176.0  0.472993  Donald Trump
1    NaN   US  Hillary Clinton  ...  127592176.0  0.477938  Donald Trump
2    NaN   US     Gary Johnson  ...  127592176.0  0.032640  Donald Trump
3    NaN   US       Jill Stein  ...  127592176.0  0.009844  Donald Trump
4    NaN   US    Evan McMullin  ...  127592176.0  0.003540  Donald Trump

[5 rows x 9 columns]

In [0]:
for df in [county_2015, pres16]:
  df.set_index(['County', 'State'], inplace=True)

In [39]:
pres16 = pres16[pres16['cand'] == 'Donald Trump']
pres16 = pres16[['pct']]
pres16.dropna(inplace=True)
pres16.head()

                   pct
County State
NaN    US     0.472993
       CA     0.330641
       FL     0.490640
       TX     0.525830
       NY     0.374752

ERROR! Session/line number was not unique in database. History logging moved to new session 59

In [0]:
all_together = county_2015.merge(pres16, on=['County', 'State'])
all_together.dropna(inplace=True)

In [41]:
all_together.drop('Year', axis=1, inplace=True)
all_together.head()

                              Month  Rate  min_wage       pct
County              State
Major County        OK     February   2.6      2.11  0.864960
Pottawatomie County OK     February   4.5      2.11  0.701342
Johnston County     OK     February   6.5      2.11  0.770057
Jefferson County    OK     February   5.0      2.11  0.812367
Beaver County       OK     February   2.8      2.11  0.888243

In [42]:
all_together.corr()

              Rate  min_wage       pct
Rate      1.000000  0.186689 -0.085985
min_wage  0.186689  1.000000 -0.325036
pct      -0.085985 -0.325036  1.000000

In [43]:
all_together.cov()

              Rate  min_wage       pct
Rate      5.743199  0.683870 -0.031771
min_wage  0.683870  2.336451 -0.076602
pct      -0.031771 -0.076602  0.023772